name = "task-manager-prod"
pages_build_output_dir = "dist"

[vars]
AUTH0_DOMAIN = "taskmanager.ca.auth0.com"
AUTH0_AUDIENCE = "https://task-manager-user/api"
AUTH0_ISSUER = "https://taskmanager.ca.auth0.com/"

VITE_AUTH0_DOMAIN = "taskmanager.ca.auth0.com"
VITE_AUTH0_AUDIENCE = "https://task-manager-user/api"
VITE_AUTH0_REDIRECT_URI = "https://task-manager-prod.pages.dev"
VITE_AUTH0_CLIENT_ID = "U7adiigDl3UV7MVxPSeh04kR5QM9G5ZZ"
VITE_AUTH0_ORG_ID = "org_VzWrWJWhWcOChctX"